server:
  port: 8082

spring:
  application:
    name: teacher-service
  datasource:
    username: root
    password: Admin123!
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://182.92.130.191:3306/test?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    type: com.alibaba.druid.pool.DruidDataSource

mybatis:
  mapper-locations: classpath:mapper/*.xml